CREATE DATABASE Meals;
GO

USE Meals;
GO
-- Create table for Hello Fresh Meals
CREATE TABLE HF_Meal(
    HFMealID INT PRIMARY KEY,
    HFMealRating INT,
    HFMealName VARCHAR(100)
);
-- Create table for Paprike 3 meals
CREATE TABLE P3_Meal(
    P3MealID INT PRIMARY KEY,
    P3MealRating INT,
    P3MealName VARCHAR(100)
);
-- Insert HF Meals into the appropriate table
INSERT INTO HF_Meal (HFMealID, HFMealRating, HFMealName)
VALUES
(1, 2, "Almond Crusted Chicken"),
(2, 2, "Bacon, Apple and Cheddar Melts"),
(3, 2, "Baked Chicken Parmesan"),
(4, 5, "BBQ Beef Meatballs"),
(5, 2, "BBQ Pork and Apple Meatballs"),
(6, 3, "BBQ-Sauced Chicken"),
(7, 4, "BBQ Steak Sandwiches"),
(8, 3, "Beef and Roasted Pepper Ragu"),
(9, 7, "Beef Taquitos"),
(10, 1, "Bodega-Inspired Beef Burgers"),
(11, 2, "Braised Chicken and Mushrooms"),
(12, 1, "Breaded Baked Chicken"),
(13, 3, "Caesar Turkey Burgers"),
(14, 2, "Cal Smart Sweet Soy Turkey Patties"),
(15, 5, "Cheesy Beef and Pork Hash"),
(16, 2, "Cheesy Beef and Rigatoni Bake"),
(17, 7, "Cheesy Pork Enchiladas"),
(18, 3, "Cheesy Pork Quesadillas"),
(19, 4, "Cheesy Stuffed Chicken and Sweet Potato Mash"),
(20, 5, "Cheesy Tex-Mex Orzo Skillet"),
(21, 4, "Chicken Chow Mein-Style Noodles"),
(22, 2, "Chinese Cashew Pork Stir-Fry"),
(23, 4, "Chicken Schnitzel"),
(24, 1, "Chicken Tikka Masala"),
(25, 2, "Chopped Cheese Quesadillas"),
(26, 4, "Fajita-Inspired Chicken Flatbreads"),
(27, 2, "Fajita Style Beef Bowls"),
(28, 3, "Farmhouse Chicken"),
(29, 3, "Fig Maple Pork Tenderloin"),
(30, 6, "French Dip Burgers"),
(31, 6, "Galactic Pork Souvlaki-Inspired Burgers"),
(32, 5, "Golden Breaded Tilapia"),
(33, 1, "Grilled Sausage Flatbreads"),
(34, 2, "Grilled Tuscan Chicken Penne"),
(35, 2, "Hearty Beef and Black Bean Chili"),
(36, 4, "Hearty Beef and Pork Ragu"),
(37, 3, "Hearty Meatball and Mushroom Stew"),
(38, 4, "Honey-Garlic Chicken Wraps"),
(39, 5, "Honey Mustard Baked Salmon"),
(40, 4, "Italian Inspired Beef Burgers"),
(41, 2, "Lemony Beef and Orzo Bowls"),
(42, 1, "Maple Balsamic Chicken"),
(43, 1, "Mediterranean Tortellini"),
(44, 3, "Mexican-Inspired Pork Quesadillas"),
(45, 6, "Miso-Honey Glazed Salmon"),
(46, 4, "Moroccan-Inspired Chicken"),
(47, 2, "One Pan Chicken and Orzo"),
(48, 1, "One-Pot Italian Sausage Soup"),
(49, 2, "One-Pot Soutwest-Style Beef and Cavatappi"),
(50, 1, "Pan-Seared Pork Chops"),
(51, 1, "Panko-Crusted Chicken"),
(52, 2, "Parmesan-Crusted Pork Chops"),
(53, 5, "Pecan-Crusted Roasted Salmon"),
(54, 4, "Pesto Turkey Bowls"),
(55, 2, "Pork and Apple Burgers"),
(56, 3, "Pork and Sweet Pepper Tacos"),
(57, 7, "Pork Chops and Mushroom-Sour Cream Sauce"),
(58, 6, "Pork Spring Roll-Inspired Bowls"),
(59, 5, "Retro Burgers"),
(60, 5, "Salisbury Steaks in Onion Gravy"),
(61, 2, "Salisbury Steak-Style Pork Patties and Mash"),
(62, 6, "Sausage Gnocchi Skillet"),
(63, 6, "Scandi-Style Salmon"),
(64, 5, "Sheet Pan Beef Koftas"),
(65, 3, "Silky Peanut-Ginger Beef and Pork Noodle Bowls"),
(66, 1, "Smart Cruchy Clementine Chicken Salad"),
(67, 3, "Smart Mexican-Inspired Chicken Patties"),
(68, 2, "Smash Burgers"),
(69, 3, "SuperQuick Southwest Turkey Salad"),
(70, 5, "Speedy BBQ Chicken Sandwiches"),
(71, 5, "Speedy Chicken Chili"),
(72, 5, "St.Baptiste Cheesy Blueberry Burgers"),
(73, 5, "Steak with Rosemary Sous Vide Potatoes"),
(74, 3, "Sticky Glazed Chicken Sammies"),
(75, 4, "Super Quick Open-Faced Speedy Sausage Sandos"),
(76, 2, "Super Quick Turkey Tacos"),
(77, 3, "Sweet Ginger Pork Stir-Fry"),
(78, 4, "Sweet n Savory Beef and Pork Noodles"),
(79, 4, "Tangy Sesame Chicken"),
(80, 5, "Super Quick Teriyaki Beef Ramen Bowls"),
(81, 5, "Tex-Mex Beef and Rice Skillet"),
(82, 5, "Tex-Mex Style Beef and Pork Skillet Rice"),
(83, 2, "Turkey Burrito Bowls"),
(84, 3, "Turkey Sloppy Joes"),
(85, 3, "Turkey Taco Pizzas"),
(86, 6, "Turkey and Fig Burgers"),
(87, 3, "Turkey and Zucchini Rigatoni"),
(88, 5, "Umami Steak and Noodle Stir-Fry"),
(89, 4, "Zesty Beef Bowls"),
(90, 7, "Oven Roasted Gnocchi");

