CREATE DATABASE Meals;
GO

USE Meals;
GO
-- Create table for Hello Fresh Meals
CREATE TABLE HF_Meal(
    HFMealID INT PRIMARY KEY,
    HFMealRating INT,
    HFMealName VARCHAR(100)
);
-- Create table for Paprike 3 meals
CREATE TABLE P3_Meal(
    P3MealID INT PRIMARY KEY,
    P3MealRating INT,
    P3MealName VARCHAR(100)
);
-- Insert HF Meals into the appropriate table
INSERT INTO HF_Meal (HFMealID, HFMealRating, HFMealName)
VALUES
(1, 2, "Almond Crusted Chicken"),
(2, 2, "Bacon, Apple and Cheddar Melts"),
(3, 2, "Baked Chicken Parmesan"),
(4, 5, "BBQ Beef Meatballs"),
(5, 2, "BBQ Pork and Apple Meatballs"),
(6, 3, "BBQ-Sauced Chicken"),
(7, 4, "BBQ Steak Sandwiches"),
(8, 3, "Beef and Roasted Pepper Ragu"),
(9, 7, "Beef Taquitos"),
(10, 1, "Bodega-Inspired Beef Burgers"),
(11, 2, "Braised Chicken and Mushrooms"),
(12, 1, "Breaded Baked Chicken"),
(13, 3, "Caesar Turkey Burgers"),
(14, 2, "Cal Smart Sweet Soy Turkey Patties"),
(15, 5, "Cheesy Beef and Pork Hash"),
(16, 2, "Cheesy Beef and Rigatoni Bake"),
(17, 7, "Cheesy Pork Enchiladas"),
(18, 3, "Cheesy Pork Quesadillas"),
(19, 4, "Cheesy Stuffed Chicken and Sweet Potato Mash"),
(20, 5, "Cheesy Tex-Mex Orzo Skillet"),
(21, 4, "Chicken Chow Mein-Style Noodles"),
(22, 2, "Chinese Cashew Pork Stir-Fry"),
(23, 4, "Chicken Schnitzel"),
(24, 1, "Chicken Tikka Masala"),
(25, 2, "Chopped Cheese Quesadillas"),
(26, 4, "Fajita-Inspired Chicken Flatbreads"),
(27, 2, "Fajita Style Beef Bowls"),
(28, 3, "Farmhouse Chicken"),
(29, 3, "Fig Maple Pork Tenderloin"),
(30, 6, "French Dip Burgers"),
(31, 6, "Galactic Pork Souvlaki-Inspired Burgers"),
(32, 5, "Golden Breaded Tilapia"),
(33, 1, "Grilled Sausage Flatbreads"),
(34, 2, "Grilled Tuscan Chicken Penne"),
(35, 2, "Hearty Beef and Black Bean Chili"),
(36, 4, "Hearty Beef and Pork Ragu"),
(37, 3, "Hearty Meatball and Mushroom Stew"),
(38, 4, "Honey-Garlic Chicken Wraps"),
(39, 5, "Honey Mustard Baked Salmon"),
(40, 4, "Italian Inspired Beef Burgers"),
(41, 2, "Lemony Beef and Orzo Bowls"),
(42, 1, "Maple Balsamic Chicken"),
(43, 1, "Mediterranean Tortellini"),
(44, 3, "Mexican-Inspired Pork Quesadillas"),
(45, 6, "Miso-Honey Glazed Salmon"),
(46, 4, "Moroccan-Inspired Chicken"),
(47, 2, "One Pan Chicken and Orzo"),
(48, 1, "One-Pot Italian Sausage Soup"),
(49, 2, "One-Pot Soutwest-Style Beef and Cavatappi"),
(50, 1, "Pan-Seared Pork Chops"),
(51, 1, "Panko-Crusted Chicken"),
(52, 2, "Parmesan-Crusted Pork Chops"),
(53, 5, "Pecan-Crusted Roasted Salmon"),
(54, 4, "Pesto Turkey Bowls"),
(55, 2, "Pork and Apple Burgers"),
(56, 3, "Pork and Sweet Pepper Tacos"),
(57, 7, "Pork Chops and Mushroom-Sour Cream Sauce"),
(58, 6, "Pork Spring Roll-Inspired Bowls"),
(59, 5, "Retro Burgers"),
(60, 5, "Salisbury Steaks in Onion Gravy"),
(61, 2, "Salisbury Steak-Style Pork Patties and Mash"),
(62, 6, "Sausage Gnocchi Skillet"),
(63, 6, "Scandi-Style Salmon"),
(64, 5, "Sheet Pan Beef Koftas"),
(65, 3, "Silky Peanut-Ginger Beef and Pork Noodle Bowls"),
(66, 1, "Smart Cruchy Clementine Chicken Salad"),
(67, 3, "Smart Mexican-Inspired Chicken Patties"),
(68, 2, "Smash Burgers"),
(69, 3, "SuperQuick Southwest Turkey Salad"),
(70, 5, "Speedy BBQ Chicken Sandwiches"),
(71, 5, "Speedy Chicken Chili"),
(72, 5, "St.Baptiste Cheesy Blueberry Burgers"),
(73, 5, "Steak with Rosemary Sous Vide Potatoes"),
(74, 3, "Sticky Glazed Chicken Sammies"),
(75, 4, "Super Quick Open-Faced Speedy Sausage Sandos"),
(76, 2, "Super Quick Turkey Tacos"),
(77, 3, "Sweet Ginger Pork Stir-Fry"),
(78, 4, "Sweet n Savory Beef and Pork Noodles"),
(79, 4, "Tangy Sesame Chicken"),
(80, 5, "Super Quick Teriyaki Beef Ramen Bowls"),
(81, 5, "Tex-Mex Beef and Rice Skillet"),
(82, 5, "Tex-Mex Style Beef and Pork Skillet Rice"),
(83, 2, "Turkey Burrito Bowls"),
(84, 3, "Turkey Sloppy Joes"),
(85, 3, "Turkey Taco Pizzas"),
(86, 6, "Turkey and Fig Burgers"),
(87, 3, "Turkey and Zucchini Rigatoni"),
(88, 5, "Umami Steak and Noodle Stir-Fry"),
(89, 4, "Zesty Beef Bowls"),
(90, 7, "Oven Roasted Gnocchi");

-- Insert P3 Meals into appropriate table
INSERT INTO P3_Meal(P3MealID, P3MealRating, P3MealName)
VALUES
(1, 5, "Cajun-Spiced Chicken and Rice Bowls"),
(2, 5, "Cast Iron Skillet Garlic & Brown Sugar Pork Chops"),
(3, 5, "Chicken Souvlaki Kebabs with Taztziki Sauce"),
(4, 5, "Chicken Zucchini Noodle Pad Thai"),
(5, 5, "Country Style Steak"),
(6, 5, "Easy Beef Bowls"),
(7, 5, "Easy Turkey & Zucchini Skillet"),
(8, 5, "Garlic Butter Chicken & Broccoli"),
(9, 5, "Garlic Mushroom Chicken Thighs"),
(10, 5, "Healthy Chicken Pot Pie Soup"),
(10, 5, "Instant Pot Ham"),
(11, 5, "Instant Pot 'Rotissserie' Chicken"),
(12, 5, "Linda Laffan's Lasagna"),
(13, 5, "Maple-Glazed Skillet Chicken Breasts with Sweet Potato Hash"),
(14, 5, "One Pot Beans and Sausages and Greens"),
(15, 5, "Phyllo-Wrapped Herbed Pork Tenderloin with Mushrooms"),
(16, 5, "Pineapple-Glazed Ham"),
(17, 5, "Quick Thai Pork Stir-Fry"),
(18, 5, "Roasted Garlic Ratatouille"),
(19, 5, "Sous Vide Smoked Brisket"),
(20, 5, "Souvlaki-Style Pork Tenderloin with Mixed Vegetables"),
(21, 5, "Spicy Ground Turkey and Green Bean Stir-Fry"),
(22, 5, "Sweet Potato Chickpea Buddha Bowl"),
(23, 5, "The Best Baked Pineapple Chicken Thighs"),
(24, 4, "Easy Balsamic Grilled Vegetables with Feta"),
(25, 4, "Miso Wanton Soup"),
(26, 4, "2 Hour Paleo Slow Cooker Beef Stew"),
(27, 5, "Pork Carnitas"),
(28, 5, "Beef and Broccoli Stirfry"),
(29, 2, "Baked Cod with Panko"),
(30, 4, "Baked Gnocchi with Bacon, Tomato and Mozzarella"),
(31, 3, "Brats and Brussel Sprouts Bowls"),
(32, 3, "Burrito Bowls with Chicken"),
(33, 3, "Cauliflower Rice Stuffed Peppers"),
(34, 2, "Chicken and Bacon Pasta with Spinach and Tomatoes in Garlic Cream Sauce"),
(35, 3, "Chicken and Rice Oh So Nice"),
(36, 3, "Chicken Detox Soup"),
(37, 2, "Crockpot Sausage and Peppers"),
(38, 4, "Garlic Chicken Stir Fry"),
(39, 4, "Ginger Salmon"),
(40, 3, "Grilled Salmon and Couscous Pouches"),
(41, 3, "Healthy Cauliflower Fried Rice"),
(42, 3, "Instant Pot Root Beer Pulled Pork"),
(43, 3, "Instant Pot Pork Roast with Vegetables and Gravy"),
(44, 3, "Lemon Garlic Baked Chicken Thighs"),
(45, 5, "Lentil Soup"),
(46, 5, "Low Carb Mushroom & Spinnach Cauliflower Rice"),
(47, 5, "Pesto Salmon Packets"),
(48, 3, "One Pot Creamy Lemon Goat Cheese Pasta with Chickpeas and Asparagus"),
(49, 2, "Roasted Greek-Style Chicken and Vegetables"),
(50, 3, "Roasted Lemon Rosemary Chicken"),
(51, 2, "Sheet Pan Roasted Brussel Sprouts, Butternut Squash, Bacon & Red Onion"),
(52, 4, "Slow-Cooker Pulled Pork Sliders with Spicy Slaw"),
(53, 3, "Sous Vide New York Steak with Homemade Chimichurri"),
(54, 4, "Sriracha Hoisin Ground Pork Bowls"),
(55, 4, "Teriyaki Salmon with Bok Choy One Pan Dinner"),
(56, 4, "Stuffed Flank Steak"),
(57, 2, "Winter Vegetable Stew");